FROM ruby:2.2

ARG APP_HOME=/app

RUN set -x \
 && echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list \
 && apt-get update -qq \
 && apt-get install -y build-essential \
 && apt-get clean

WORKDIR $APP_HOME

COPY Gemfile* $APP_HOME/
RUN bundle install
COPY . $APP_HOME/

ENV COMMENT_DATABASE_HOST=comment_db COMMENT_DATABASE=comments

CMD ["puma"]
