apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  #namespace: default
  labels:
    app: reddit
    component: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: ui
  template:
    metadata:
      name: ui-pod
      labels:
        app: reddit
        component: ui
    spec:
      containers:
        - name: ui
          image: skyfly534/ui
          env:
          - name: ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      # imagePullSecrets:
      #   - name: regcred
